const mongoose=require('mongoose')

const userSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    username:{
        type:String,
        required:true
    },
    number:{
        type:Number,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    admin:{
        type:Boolean,
        default:false
    },
    varified:{
        type:Boolean,
        default:true
    },
    image:{
        type:String,
        default:false
    },
    address:[
        {
           type:{
               type:String,
           },
           houseName:{
               type:String,
           },
           village:{
               type:String,
           },
           landmark:{
               type:String
           },
           pincode:{
               type:Number,
           },
           city:{
               type:String,
           },
           district:{
               type:String,
           },
           state:{
               type:String,
           },
           country:{
               type:String
           }
       }
     ]
})

module.exports=mongoose.model('User',userSchema)